### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by upamaru0104** [upamaru0104/furima-39197#21]
自身のフリマアプリのURL | https://furima-39197.onrender.com

Basic認証のIDとパスワード |  admin,2222
出品者用のメールアドレスとパスワード | abc@abc,abc000
購入者用のメールアドレスとパスワード | def@def,def000

**Comment by mo1015** [comment]
@upamaru0104 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されること（--- は初期値として設定すること）**
「目立った傷や汚れ無し」を要件通り「目立った傷や汚れなし」に修正しましょう。

- [x] **出品ページにて、エラーハンドリングの際、重複したエラーメッセージが表示されないこと**
「Price can't be blank」というエラーメッセージが重複して表示されます。

- [x] **編集ページにて、 エラーハンドリングの際、重複したエラーメッセージが表示されないこと**
「Price can't be blank」というエラーメッセージが重複して表示されます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by upamaru0104** [comment]
修正しました

**Comment by shodai-ito** [comment]
@upamaru0104 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
